name: CI
on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies]
        shell: sh
        run: poetry install
      - name: linting
        run: poetry run flake8 ./
      - name: testing
        run: poetry run pytest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying"
      

